### ISSUE TITLE
Will Tailscale OAuth authentication be supported ?

### ISSUE THREAD

**Issue by exo-cedric** [tailscale/gitops-acl-action#19]
<-> (removed link)

(such as to work around the Max. 90 days API Key TTL)

**Comment by DentonGentry** [comment]
That doc isn't publicly searchable yet, the feature isn't in Alpha but is being prepared for it. It was made available to a very small number of sites, presumably including yours, as early access.

I've edited the issue to remove the link, we are not ready for a larger number of sites to start trying to use it.

I do expect to add support for OAuth API endpoints in this and other areas where we've produced something which needs a key. That work isn't done, and hasn't been started yet for some of them, because the OAuth feature isn't actually available yet for use.

**Comment by korenyoni** [comment]
See https://github.com/tailscale/gitops-acl-action/pull/20

```yaml
name: Sync Tailscale ACLs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  acls:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # https://tailscale.com/kb/1215/oauth-clients/#generating-long-lived-auth-keys
      # https://www.aaron-powell.com/posts/2022-07-14-working-with-add-mask-and-github-actions/
      - name: Generate API Token from OAuth App
        run: |
          TS_API_TOKEN=$(curl -d "client_id=${{ secrets.TS_OAUTH_CLIENT_ID }}" -d "client_secret=${{ secrets.TS_OAUTH_CLIENT_SECRET }}" \
            "https://api.tailscale.com/api/v2/oauth/token" | jq -r '.access_token')
          echo "::add-mask::$TS_API_TOKEN"
          echo TS_API_TOKEN=$TS_API_TOKEN >> $GITHUB_ENV
      - name: Deploy ACL
        if: github.event_name == 'push'
        id: deploy-acl
        uses: tailscale/gitops-acl-action@v1
        with:
          api-key: ${{ env.TS_API_TOKEN }}
          tailnet: ${{ secrets.TS_TAILNET }}
          action: apply
          policy-file: tailscale/policy.hujson

      - name: Test ACL
        if: github.event_name == 'pull_request'
        id: test-acl
        uses: tailscale/gitops-acl-action@v1
        with:
          api-key: ${{ env.TS_API_TOKEN}}
          tailnet: ${{ secrets.TS_TAILNET }}
          action: test
          policy-file: tailscale/policy.hujson
```
