### ISSUE TITLE
Testing working configs now fails

### ISSUE THREAD

**Issue by a1ecbr0wn** [tailscale/gitops-acl-action#45]
Without changing my ACL or build, I now always get the following error when testing on github:

```
Run go run tailscale.com/cmd/gitops-pusher@v1.66.4 "--policy-file=policy.hujson" "test"
go: downloading tailscale.com v1.66.4
go: downloading github.com/peterbourgon/ff/v3 v3.4.0
go: downloading github.com/tailscale/hujson v0.0.0-20221223112325-20486734a56a
go: downloading golang.org/x/oauth2 v0.16.0
go: downloading go4.org/mem v0.0.0-20220726221520-4f986261bf13
go: downloading golang.org/x/sys v0.18.0
go: downloading github.com/mitchellh/go-ps v1.0.0
go: downloading github.com/fxamacker/cbor/v2 v2.5.0
go: downloading github.com/hdevalence/ed25519consensus v0.2.0
go: downloading golang.org/x/crypto v0.21.0
go: downloading go4.org/netipx v0.0.0-20231129151722-fdeea329fbba
go: downloading github.com/jsimonetti/rtnetlink v1.4.0
go: downloading github.com/mdlayher/netlink v1.7.2
go: downloading github.com/x448/float16 v0.8.4
go: downloading filippo.io/edwards25519 v1.1.0
go: downloading github.com/josharian/native v1.1.1-0.20230202152459-5c7d0dd6ab86
go: downloading github.com/mdlayher/socket v0.5.0
go: downloading golang.org/x/net v0.23.0
go: downloading golang.org/x/sync v0.6.0
go: downloading golang.org/x/text v0.14.0
wanted HTTP status code 200 but got 401
exit status 1
```

This is the job in my workflow that is failing:

```
jobs:
  acls:
    runs-on: ubuntu-latest

    steps:
        
      - uses: actions/checkout@v4

      - name: Test ACL
        id: test-acl
        uses: tailscale/gitops-acl-action@v1
        with:
          policy-file: policy.hujson
          api-key: ${{ secrets.TS_API_KEY }}
          tailnet: ${{ secrets.TS_TAILNET }}
          action: test
```
